name: DM-KD
favicon: null
layout_spectrum: 0.81676
typography_spectrum: 0.43411
title: DM-KD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01d1ff'
    - '#000000'
    - '#bcbcbc'
    - '#737373'
  brandStrength: 1
  lightness: 0.7027117814868689
  saturation: 0.699118128977716
  rhythmicContrast: 0.75
purpose: []
