name: DM-KD
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43411
title: DM-KD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfbf9'
    - '#25211e'
    - '#615851'
    - '#b3a396'
  brandStrength: 0.5625
  lightness: 0.7027117814868689
  saturation: 0.699118128977716
  rhythmicContrast: 0.75
purpose: []
