name: DM-KD
favicon: null
layout_spectrum: 0.5392093963455409
typography_spectrum: 0.9394479393959045
title: DM-KD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.21306869643740356
  lightness: 0.7027117814868689
  saturation: 0.699118128977716
  rhythmicContrast: 0.18157756282016635
purpose: []
