name: DM-KD
favicon: null
layout_spectrum: 0.75568
typography_spectrum: 0.49803
title: DM-KD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25252d'
    - '#5c91a3'
    - '#ffffff'
    - '#a89265'
    - '#b5c9d7'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
