name: DM-KD
favicon: null
layout_spectrum: 0.81676
typography_spectrum: 0.43411
title: DM-KD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c6f7e'
    - '#201e1b'
    - '#83a8b1'
    - '#ffffff'
    - '#cfcfcf'
  brandStrength: 0
  lightness: 0.7027117814868689
  saturation: 0.699118128977716
  rhythmicContrast: 0.75
purpose: []
